# Una mezcla de todo lo que hemos hecho hoy anotonio ^̮^
c="Caldo"
a=2
print("Caldo???????")
print(c)
print("Cuanto??????")
print(a)
print("Seguro?????????")
print("no")
print(a+4)
print("Seguro??????????")
print("no")
print(a*a)
print("Seguro???????")
print("si")
inpu=input("Escribe algo porfi")
print("vale "+inpu+" hehehehe")
print("ahora calcular")
b=input("num 1: ")
c=input("num 2: ")
print(b+c)
